delete note by id api created
RealEskalate/Practice pull request #67
Opened 2021-08-04 21:36 UTC by Tek58

2021-08-05 06:42 UTC, enochadane reviewed
inside the controller file for note there is a variable 'c' that you haven't used anywhere. Can you remove that and commit again?

2021-08-05 09:14 UTC, enochadane requested changes
Good job. remove variable c from controllers/note.ts since you are not using it anywhere.

2021-08-06 08:10 UTC, enochadane approved these changes

2021-08-06 08:41 UTC, Kaleab-git approved these changes

2021-08-06 17:49 UTC, merged